project_id = "isqbduxgxroysrojtseq"

[functions.get-otp]
verify_jwt = false

[functions.fetch-email-codes]
verify_jwt = false

[functions.generate-2fa]
verify_jwt = false

[functions.fetch-phone-code]
verify_jwt = false

[functions.check-discord-trials]
verify_jwt = false

[functions.check-discord-tokens]
verify_jwt = false

[functions.get-discord-link]
verify_jwt = false

[functions.discord-link]
verify_jwt = false

[functions.fetch-unlock-email]
verify_jwt = false

[functions.check-token-flags]
verify_jwt = false

[functions.check-token-age]
verify_jwt = false

[functions.make-tokens-nocap]
verify_jwt = false

[functions.change-discord-pass]
verify_jwt = false

[functions.fetch-outlook-emails]
verify_jwt = false

[functions.discord-email-verify]
verify_jwt = false
